### ISSUE TITLE
Way to parse imaris metadata.txt file

### ISSUE THREAD

**Issue by kushaangupta** [CBI-PITT/imaris_ims_file_reader#7]
Thanks for the useful library. I have been trying to parse the metadata produced as a separate file by imaris with postfix `_metadata.txt`. I was wondering if there is a way to parse it into a python dictionary or JSON format?

**Comment by AlanMWatson** [comment]
I need more details.  Can you provide a file?  Also, where/how is this _metadata.txt file created?  Are you trying to use this with our reader?  Thanks

**Comment by AlanMWatson** [comment]
stale
